name: Publish Package to PyPI

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/FindSystemFontsFilename
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: "Install build"
      run: pip install build

    - name: Build package
      run: python -m build
  
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

