name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: "Test (${{matrix.os}}, Python ${{ matrix.python-version }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python requirements
      run: pip install --upgrade --upgrade-strategy eager .

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest

  run-tests-cygwin:
    name: "Test Cygwin"
    runs-on: 'windows-latest'

    # Use cygwin bash
    # From: https://github.com/marketplace/actions/install-cygwin#line-terminators
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'

    steps:
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: python3
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python requirements
      run: |
        pip3 install --upgrade --upgrade-strategy eager $(cygpath --absolute $GITHUB_WORKSPACE)

    - name: Install pytest
      run: |
        pip3 install pytest

    - name: Run tests
      run: |
        pytest $(cygpath --absolute $GITHUB_WORKSPACE)

  run-tests-msys2:
    name: "Test MSYS2"
    runs-on: 'windows-latest'

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }


    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: >-
          mingw-w64-${{matrix.env}}-python
          mingw-w64-${{matrix.env}}-python-pip

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python requirements
      run: |
        which python
        which pip3
        which pip
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade --upgrade-strategy eager .
        pip install pytest
        pytest
