name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run-tests:
    name: "Test (${{matrix.os}}, Python ${{ matrix.python-version }}, ${{ matrix.architecture }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        architecture: [x64, x86, arm64]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: ubuntu-latest
            architecture: arm64
          - os: windows-latest
            architecture: arm64
          - os: macos-latest
            architecture: x86
          - os: macos-latest
            architecture: x64
          - os: macos-latest
            architecture: x86

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install Python requirements
      run: pip install --upgrade --upgrade-strategy eager .

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest
