name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run-tests:
    name: "Test (${{matrix.os}}, Python ${{ matrix.python-version }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python requirements
      run: pip install --upgrade --upgrade-strategy eager .

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest

  test-freebsd:
    name: "Test on FreeBSD (${{matrix.python-version}})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["python39"] # python 3.12 isn't available on FreeBSD
        include:
          - python-version: "python39"
            pip-package: "py39-pip"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg update
          pkg install -y libX11
          pkg install -y ${{matrix.python-version}}
        run: |
          python3.9 -m ensurepip --upgrade
          python3.9 -m pip install --upgrade --upgrade-strategy eager .
          python3.9 -m pip install pytest
          python3.9 -m pytest
